### ISSUE TITLE
Problems accessing subpages and options

### ISSUE THREAD

**Issue by rantonse** [sylvainjule/kirby-bouncer#10]
Hi, and thank you for a great plugin!

I’m having some problems accessing _subpages_ after updating to 1.0.4. There are also problems with the options; for example, I get “The dropdown is empty” when trying to click on “...” in cards or access the settings menu.

I verified the error with a clean install of the starter kit.

**Comment by rantonse** [comment]
My temporary fix – probably _not_ what you want to do – was to replace [line 26–28](https://github.com/sylvainjule/kirby-bouncer/blob/be31b1d14b10f1ce7758e9b98803febba9490cf6/index.php#L26) in `index.php`
```
if(!in_array($currentPath, $allowedPaths)) {
  Panel::go($allowedPaths[0]);
}
```
with the following:
```
$pathfound = false;
foreach ($allowedPaths as $allowedPath) {
  if (strpos($currentPath, $allowedPath) === 0) {
    $pathfound = true;
    }
  }
if (!$pathfound) {
  Panel::go($allowedPaths[0]);
}
```

**Comment by rantonse** [comment]
However, the above “fix” does not do anything for the problem with the options and dropdowns.

**Comment by kerli81** [comment]
I hope the pull request #11 fixes the issue.

**Comment by destrosvet** [comment]
> I hope the pull request #11 fixes the issue.

It solved subpage problem (can acces and edit now) but when try to add I got "The dialog component does not exist" (Kirby 3.6.1.1)

**Comment by rantonse** [comment]
I’m getting the same message. Any updates?

**Comment by sylvainjule** [comment]
I cannot reproduce with the latest commit (neither in 3.6.1.1 nor 3.6.2), can you? If so, could you give more details about your config?

**Comment by rantonse** [comment]
I can no longer reproduce. All seems good! Thank you.
