### ISSUE TITLE
add comment to config snippet

### ISSUE THREAD

**Issue by bnomei** [sylvainjule/kirby-bouncer#15]
i copied the snippet but decided to change the blueprint name and forgot about the config value since everything else seemed to work. a small comment (not just the information in the sentence above the snippet) could help spot this mistake later on.

```php
return [
    'sylvainjule.bouncer.list' => [
        'test' => [ // match the filename without extension of the user blueprint
            'fieldname' => 'canaccess'
        ]
    ]
];
```

**Comment by sylvainjule** [comment]
Added, thanks! ✓
