### ISSUE TITLE
Better fields list declaration

### ISSUE THREAD

**Issue by ronaldtorres** [sylvainjule/kirby-bouncer#2]
Hello,
first of all, thank you for this plugin!

I think that the way as the field are declared may can be improved.

An example can be:

```php
'sylvainjule.bouncer.list' => [
    'author' => [
        'fieldname' => 'access',
        'nav' => true
    ],
    'blog-editor' => [
        'fieldname' => 'access',
        'nav' => true
    ],
    'contributor' => [
        'fieldname' => 'access',
        'nav' => true
    ],
    'moderator' => [
        'fieldname' => 'access',
        'nav' => true
    ],
    'examplerole' => [
        'fieldname' => 'onlyAccess',
    ],
],
```

A more reusable way can be by adding the fields as keys and the roles inside as array|string.

Something like this:
```php
'sylvainjule.bouncer.list' => [
    'access' => [
        'roles' => ['author', 'blog-editor', 'contributor', 'moderator'],
        'nav' => true
    ],
    'onlyAccess' => [
        'roles' => 'exampleRole',
    ],
]
```

Is only a suggestion 🙂

EDIT: The disadvantage is when you want the same field name with different options as the nav value.

**Comment by ronaldtorres** [comment]
Thinking better, I know that the role is the more fastest and effective way to associate the role with the field, but i leave the issue active to know what you thinking about it. :)

**Comment by sylvainjule** [comment]
Thanks for the suggestion, I understand how this could be faster when you to setup a lot of roles, but also think that the current way is the most flexible one, to fine-tune specific options for each roles. So I'll keep it like this! 👀
