### ISSUE TITLE
Questions about Bouncer plugin and Permissions

### ISSUE THREAD

**Issue by benhatfield** [sylvainjule/kirby-bouncer#29]
Hello,

We’re attempting to use the Bouncer plugin because we'd like users to only have access to certain content pages, but we also want some of them to be able to edit users.

Is that possible with this plugin?

screenshot of bouncer settings from site/blueprints/users/staff.yml
![Screenshot 2023-11-21 at 11 16 17 AM](https://github.com/sylvainjule/kirby-bouncer/assets/29380066/bfec3aa4-71ca-4be7-8854-268002f2d4a1)

**Comment by sylvainjule** [comment]
Unfortunately it is not possible with this plugin and I don't plan to extend it that way. The ability for a user to modify other users' forms, but not their own could quickly lead to a maze of permissions and would be harder to maintain.
