### ISSUE TITLE
Incompatible with 3.6.0

### ISSUE THREAD

**Issue by distantnative** [sylvainjule/kirby-bouncer#8]
Hi Sylvain,

As you can see from he alpha version of 3.6.0 (https://getkirby.com/releases/3.6), we will remove `vue-router` with this release. Which of course means that your plugin's functionality would be rendered broken. 

However, in anticipation we added two hooks
- https://github.com/getkirby/kirby/blob/develop/src/Panel/Panel.php#L279
- https://github.com/getkirby/kirby/blob/develop/src/Panel/Panel.php#L308

I would believe that with the `panel.route:before` hook, we could recreate your plugin. Likely even much simpler than the current setup. Let me know your thoughts - happy to collaborate.

**Comment by namlit4** [comment]
hi, any news on this issue? would be awesome to have bouncer working with 3.6!

**Comment by sylvainjule** [comment]
Hi Nico,

Apologies for the delay in addressing this. Thanks a lot for taking the time to identify the issue and pointing me in those directions! This sounds great and I also feel that it will allow to come up with a much simpler setup. 

Although for now, I don't get how to trigger a redirect from the hook. As a first test, I've tried using `Panel::go('...')` but without success:

```php
'hooks' => [
    'panel.route:before' => function($route, $path, $method) {
        if($path != 'pages/annotator') {
            Panel::go('pages/annotator');
        }
    }
]
``` 

Ends up with an error on click anywhere when I'm already on this page, and this screen anytime else:

<img width="1392" alt="Capture d’écran 2021-11-24 à 16 07 40" src="https://user-images.githubusercontent.com/14079751/143265157-fe33fd2c-03c1-4808-b4cc-894d09cf11b6.png">

It redirects with the simple `go('panel/...')`, but of course without the proper routing stuff / language / etc. that should happen.

Am I overlooking something?
I've just started to dig into this so I might be missing something obvious, I'll keep looking but in the meantime if you have any advice, I'd gladly take them :)

**Comment by distantnative** [comment]
Indeed, I think we would need to move this https://github.com/getkirby/kirby/blob/main/src/Panel/Panel.php#L305-L312 inside the try-catch block that follows. Could you try if that would work for you?

**Comment by sylvainjule** [comment]
Awesome, it does!

**Comment by distantnative** [comment]
Let's see if we can get it in 3.6.1 https://github.com/getkirby/kirby/pull/3964

**Comment by sylvainjule** [comment]
Awesome! I'll get working on the plugin based on this.

**Comment by sylvainjule** [comment]
Seems like it's good to go on the `next` branch, when 3.6.1 rolls out :)

**Comment by distantnative** [comment]
Awesome
